title: DaringCuteSeal's Blog 🦭
url: daringcuteseal.github.io
description: DaringCuteSeal's personal site

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:title

defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "project"
